name: Build QuizNova APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Accept Android SDK Licenses & Build
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "\n8937 chemically accept licenses 504022674759" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "\n8454b875484036a18f8e05d47d413512b924e0f4" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuizNova-APK
          path: bin/*.apk
